### ISSUE TITLE
rockchip platform,run moonlight-qt,report "Segmentation fault"

### ISSUE THREAD

**Issue by GeorgeWang12356** [cgutman/moonlight-qt#1082]
**READ ME FIRST!**
If you're here because something basic is not working (like gamepad input, video, or similar), it's probably something specific to your setup, so make sure you've gone through the Troubleshooting Guide first: https://github.com/moonlight-stream/moonlight-docs/wiki/Troubleshooting

If you still have trouble with basic functionality after following the guide, join our Discord server where there are many other volunteers who can help (or direct you back here if it looks like a Moonlight bug after all). https://moonlight-stream.org/discord

**Describe the bug**
Moonlight qt runs with SDL versions 2.0.20 and above, and will report segment errors, but I can run normally with versions below 2.0.20.

However, I cannot use versions below SDL 2.0.20 because there are related issues with versions below SDL 2.0.20. I must use versions 2.0.20 and above (I need to use Wayland as the video driver for SDL)

**Steps to reproduce**

**Screenshots**
![image](https://github.com/moonlight-stream/moonlight-qt/assets/13636697/f93d7ed4-d4fe-451c-a95c-15354f93fc24)

**Affected games**

**Other Moonlight clients**

**Moonlight settings (please complete the following information)**

**Gamepad-related issues (please complete if problem is gamepad-related)**

**Client PC details (please complete the following information)**
 - OS: [buildroot weston wayland]
 - Moonlight Version: [v4.3.1]
 - GPU: [rockchip rk3566 mali400]

**Server PC details (please complete the following information)**
 - OS: [rockchip rk3566 mali400]
 - GeForce Experience version: [rockchip rk3566 mali400]
 - Nvidia GPU driver: [537.13]
 - Antivirus and firewall software: [all close]

**Moonlight Logs (please attach)**
root@RK356X:~# ./moonlight stream 10.0.9.93 mstsc
00:00:00 - Qt Warning: QStandardPaths: runtime directory '/var/run' is not a directory, but a symbolic link to a directory permissions 0755 owned by UID 0 GID 0
00:00:00 - SDL Info (0): Compiled with SDL 2.0.20
00:00:00 - SDL Info (0): Running with SDL 2.0.22
00:00:00 - Qt Info: No translation available for "C"
00:00:00 - SDL Info (0): Detected Wayland
arm_release_ver of this libmali is 'g2p0-01eac0', rk_so_ver is '3'.00:00:00 - Qt Warning: qrc:/gui/main.qml:12:1: QML ApplicationWindow: ToolTip must be attached to an Item
00:00:00 - Qt Info: Found "gamecontrollerdb.txt" at "/root/.cache/Moonlight Game Streaming Project/Moonlight/gamecontrollerdb.txt"
00:00:00 - SDL Info (0): Loaded 318 new gamepad mappings
00:00:00 - SDL Info (0): Unmapped joystick: gsensor 000000006773656e736f720000000000
00:00:00 - SDL Info (0): Number of axes: 3 | Number of buttons: 0 | Number of hats: 0
xkbcommon: ERROR: couldn't find a Compose file for locale "C"
arm_release_ver of this libmali is 'g2p0-01eac0', rk_so_ver is '3'.00:00:00 - SDL Info (0): V-sync disabled
00:00:00 - SDL Info (0): Opened DRM render node: /dev/dri/renderD128
00:00:00 - SDL Info (0): Direct rendering via DRM is disabled
00:00:00 - SDL Info (0): DRM backend supports exporting EGLImage
00:00:00 - SDL Info (0): Color buffer is: R8G8B8A0
00:00:00 - SDL Info (0): EGL passed preflight checks. Using EGL for GL context creation.
00:00:00 - SDL Info (0): Using DRM renderer
00:00:00 - FFmpeg: [AVBSFContext @ 0x282d840] The input looks like it is Annex B already
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x282cd60] Initializing RKMPP decoder.
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x282cd60] RKMPP decoder initialized successfully.
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x282cd60] Wrote 445 bytes to decoder
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x282cd60] Decoder noticed an info change (1280x720), format=1
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x28684d0] Unsupported format: (null).
00:00:00 - SDL Warn (0): Test decode failed (avcodec_send_packet): Invalid argument
00:00:00 - SDL Info (0): Opened DRM render node: /dev/dri/renderD128
00:00:00 - SDL Info (0): Direct rendering via DRM is disabled
00:00:00 - SDL Info (0): Opened DRM render node: /dev/dri/renderD128
00:00:00 - SDL Info (0): Direct rendering via DRM is disabled
00:00:00 - SDL Info (0): DRM backend supports exporting EGLImage
00:00:00 - SDL Info (0): Color buffer is: R8G8B8A0
00:00:00 - SDL Info (0): EGL passed preflight checks. Using EGL for GL context creation.
00:00:00 - SDL Info (0): Using DRM renderer
00:00:00 - FFmpeg: [AVBSFContext @ 0x2865800] The input looks like it is Annex B already
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x2864b40] Initializing RKMPP decoder.
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x2864b40] RKMPP decoder initialized successfully.
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x2864b40] Wrote 445 bytes to decoder
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x2864b40] Decoder noticed an info change (1280x720), format=1
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x28659d0] Unsupported format: (null).
00:00:00 - SDL Warn (0): Test decode failed (avcodec_send_packet): Invalid argument
00:00:00 - SDL Info (0): Opened DRM render node: /dev/dri/renderD128
00:00:00 - SDL Info (0): Direct rendering via DRM is disabled
00:00:00 - SDL Info (0): Opened DRM render node: /dev/dri/renderD128
00:00:00 - SDL Info (0): Direct rendering via DRM is disabled
00:00:00 - SDL Info (0): DRM backend supports exporting EGLImage
00:00:00 - SDL Info (0): Color buffer is: R8G8B8A0
00:00:00 - SDL Info (0): EGL passed preflight checks. Using EGL for GL context creation.
00:00:00 - SDL Info (0): Using DRM renderer
00:00:00 - FFmpeg: [AVBSFContext @ 0x285c660] The input looks like it is Annex B already
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x285b9d0] Initializing RKMPP decoder.
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x285b9d0] RKMPP decoder initialized successfully.
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x285b9d0] Wrote 445 bytes to decoder
00:00:00 - FFmpeg: [hevc_rkmpp @ 0x285b9d0] Decoder noticed an info change (1280x720), format=1
00:00:00 - FFmpeg: [AVHWFramesContext @ 0x285c870] Unsupported format: (null).
00:00:00 - SDL Warn (0): Test decode failed (avcodec_send_packet): Invalid argument
00:00:00 - SDL Info (0): Opened DRM render node: /dev/dri/renderD128
00:00:00 - SDL Info (0): Direct rendering via DRM is disabled
00:00:00 - SDL Error (0): Unable to load FFmpeg decoder
00:00:00 - SDL Info (0): V-sync disabled
00:00:00 - SDL Info (0): Opened DRM render node: /dev/dri/renderD128
00:00:00 - SDL Info (0): Direct rendering via DRM is disabled
00:00:00 - SDL Info (0): DRM backend supports exporting EGLImage
00:00:01 - SDL Info (0): Color buffer is: R8G8B8A0
00:00:01 - SDL Info (0): EGL passed preflight checks. Using EGL for GL context creation.
00:00:01 - SDL Info (0): Using DRM renderer
00:00:01 - FFmpeg: [AVBSFContext @ 0x22ad510] The input looks like it is Annex B already
00:00:01 - FFmpeg: [hevc_rkmpp @ 0x2863eb0] Initializing RKMPP decoder.
00:00:01 - FFmpeg: [hevc_rkmpp @ 0x2863eb0] RKMPP decoder initialized successfully.
00:00:01 - FFmpeg: [hevc_rkmpp @ 0x2863eb0] Wrote 335 bytes to decoder
00:00:01 - FFmpeg: [hevc_rkmpp @ 0x2863eb0] Decoder noticed an info change (1280x720), format=0
00:00:01 - FFmpeg: [hevc_rkmpp @ 0x2863eb0] Wrote 335 bytes to decoder
00:00:01 - FFmpeg: [hevc_rkmpp @ 0x2863eb0] Received a frame.
rga_api version 1.3.2_[0] (RGA is compiling with meson base: $PRODUCT_BASE)
Segmentation fault

**Additional context**
Anything else you think may be relevant to the issue

**Comment by cgutman** [comment]
How are you getting/compiling moonlight-qt and which distro are you running on? We don't produce any official packages that use SDL versions as old as 2.0.20 or 2.0.22, so this must be custom built or a third party package.

Are you running code from the master branch or the v4.3.1 release?

Can you get a backtrace of the crash? Run moonlight with `gdb moonlight-qt` then enter `run` at the prompt and finally enter `bt` at the prompt when it crashes. Copy the output of that command to the issue here.

**Comment by cgutman** [comment]
Much of that code there has changed quite significantly since the v4.3.1 release. Can you try compiling the latest version currently in master (6eb5e070078174384de726501bc2510493cc4bea)? If it still crashes, please get logs and a backtrace from that version too.
