### ISSUE TITLE
Windows - Moonlight QT - Middle Mouse Button Not Working

### ISSUE THREAD

**Issue by Sloanstar** [cgutman/moonlight-qt#121]
**Describe the bug**
Middle mouse button not transmitted to / detected by host PC. (USB Connected Razer Naga)

**Steps to reproduce**
Attempt  to use / map middle mouse button (Mouse 3) in a game while connected via Moonlight.

**Screenshots**
N/A

**Moonlight settings (please complete the following information)**
- Have any settings been adjusted from defaults? Tried with and without mouse acceleration.
- If so, which settings have been changed?
- Does the problem still occur after reverting settings back to default? Yes

**Client PC details (please complete the following information)**
 - OS: Windows 10 1803
 - Moonlight Version: v0.6.2

**Logs (please attach)**
[Moonlight-1540860366.log](https://github.com/moonlight-stream/moonlight-qt/files/2527653/Moonlight-1540860366.log)
[Moonlight-1540862003.log](https://github.com/moonlight-stream/moonlight-qt/files/2527654/Moonlight-1540862003.log)

**Additional context**

**Comment by cgutman** [comment]
Middle click is working fine for me on Moonlight v0.6.2 and Windows 10 1809. GFE 3.15.0.186 on the host, same as you.

I tested by streaming the desktop, then middle-clicking a link in Chrome to open in a new tab. Can you see if that works for you too?
