### ISSUE TITLE
Audio Issue - Crackling sounds when audio is played on the remote/server PC

### ISSUE THREAD

**Issue by Byron1c** [cgutman/moonlight-qt#152]
**Describe the bug**
After installing the 0.8 Windows 10 x64, any audio played on the remote PC crackles / has static

**Steps to reproduce**
Installed 0.8 Windows 10 x64 client. All sounds from the connected PC then produced the same crackling noise. Uninstalling 0.8, and reinstalling the 0.7 client resulted in (nearly) clear audio. 

**Screenshots**
- (Im unable to attach audio recording comparisons for 0.7 and 0.8 to this report)

**Affected games**
- Any / All. Also occurs when playing audio through the remote desktop (ie) MusicBee 

**Moonlight settings (please complete the following information)**
- 1080p Settings
- All others default
- Does the problem still occur after reverting settings back to default?     Yes

**Client PC details (please complete the following information)**
 - OS: Windows 10 x64 
 - Moonlight Version: 0.7 and 0.8

**Server PC details (please complete the following information)**
 - OS:  Windows 10 1809
 - GeForce Experience version:  3.16.0.140
 - Nvidia GPU driver: 417.35

**Moonlight Logs (please attach)**
- Attached
- Audio recordings available if required

**Additional context**
- PC running Moonlight: Lenovo W510, Quadro FX880M. Connexant 20585 Audio device
- Wifi AC 5ghz network
- After recording audio comparisons, I did notice a small/minor amount of crackling in the audio in 0.7 too. The source recording has this too (ie. its not an artifact from compression).

Additional Info: 
- I have tried uninstalling/rebooting/reinstalling Moonlight without success
- Drivers: Ive reinstalled audio drivers on the client pc, both Windows generic, and manufacturers
- No crackling can be heard when I connect to the same machine through the Android client
- Dropping streaming quality didnt help
- Tried each Moonlight setting to see if it affected anything
- LatencyMon is reporting my system is suffering from buffer underruns

[Moonlight_Game_Streaming_Client_20181231122408_000_Moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/2717677/Moonlight_Game_Streaming_Client_20181231122408_000_Moonlight.log)
[Moonlight_Game_Streaming_Client_20181231122408.log](https://github.com/moonlight-stream/moonlight-qt/files/2717678/Moonlight_Game_Streaming_Client_20181231122408.log)

**Comment by Byron1c** [comment]
Additional Info: 
* I have tried uninstalling/rebooting/reinstalling Moonlight without success
* Drivers: Ive reinstalled audio drivers on the client pc, both Windows generic, and manufacturers
* No crackling can be heard when I connect to the same machine through the Android client
* Dropping streaming quality didnt help
* Tried each Moonlight setting to see if it affected anything

**Comment by cgutman** [comment]
Those are the installer logs. Can you get the client logs? They start with `Moonlight-`

**Comment by Byron1c** [comment]
Hi Cameron,
Sorry about that. No worries on the audio. Here is the log file, and links to the audio comparisons.

[Moonlight-1546288793.log](https://github.com/moonlight-stream/moonlight-qt/files/2718914/Moonlight-1546288793.log)

0.7 Sound: https://www.dropbox.com/s/8ln9a66m2mj8n89/Moonlight%200.7%20No%20Crackle.mp4?dl=0 
0.8 Sound: https://www.dropbox.com/s/g67x27cl0odaai9/Moonlight%200.8%20CRACKLE.mp4?dl=0

**Comment by cgutman** [comment]
Wow, that's definitely bad. I wonder if your older audio device doesn't like the small buffer size like newer audio devices do. I'll try to get you some builds to test with possible fixes.

**Comment by Byron1c** [comment]
Cool, thanks for looking into it. I am okay with you saying "your machine is just too old" :) No problems on running tests for you too.
Thanks again for an excellent piece of software.

**Comment by NodokaMurmevent** [comment]
hello, i hade previously the same problem i correct him on changing some parameter on pulseaudio
 (client PC )
file : 
` ~/.config/pulse/daemon.conf`

i change one line like this :
```
default-sample-format = s24le
```
previously : s32le 


Fo windows (on the client) you can try to downgrade your sound device to 16 or 32 bits 
sound > config panel > your output > property > advanced > default format

**Comment by Byron1c** [comment]
Hi - thanks for the info, but Im not running PulseAudio (AFAIK). I did a full search of my PC and couldnt find daemon.conf. I also checked the portable Moonlight folder, my %appdata% folders, and my Documents. Is there somewhere else I should look? 
I also checked that setting for my sound card, and my card is set to 16bit //44.1khz
Cheers

**Comment by NodokaMurmevent** [comment]
ho sorry i forget to precise pulseaudio it's for linux

**Comment by cgutman** [comment]
@Byron1c hah, I was actually able to reproduce the issue by setting my sound card to 16-bit 44.1KHz.

**Comment by cgutman** [comment]
@Byron1c Give this build a shot - https://ci.appveyor.com/project/cgutman/moonlight-qt/builds/21372801/job/iwg2pefdc2p53qie/artifacts

Use the portable version, not the installer (otherwise you will need to uninstall your existing build before installing the dev build).

**Comment by Byron1c** [comment]
The test build works great with clear audio :)  I then upped it to my usual 1080p and its perfectly fine.
😄

**Comment by Williangalvani** [comment]
> `~/.config/pulse/daemon.conf`
> 
> i change one line like this :
> 
> ```
> default-sample-format = s24le
> ```

This seemed to solve the audio crackling issue in Arch Linux for me.
Actually solved the issue when using other Qt app as well (QGroundControl).

Thanks a lot!
