### ISSUE TITLE
HEVC not working on RPI4 fedora 34

### ISSUE THREAD

**Issue by Barborica-Alexandru** [cgutman/moonlight-qt#654]
**Describe the bug**
HEVC decoding not working on a raspberrypi with fedora 34

**Steps to reproduce**
Install fedora 34
build moonlight release
run moonlight release
set decoder to hardware and format to h265

**Moonlight settings (please complete the following information)**
forced harware decoding

**Client PC details (please complete the following information)**
 - OS: Fedora 34
 - Moonlight Version: 3.1.4
 - GPU: Broadcom VideoCore

**Server PC details (please complete the following information)**
 - OS: Windows 10
 - GeForce Experience version: latest
 - Nvidia GPU driver: latest
 - Antivirus and firewall software: Windows Defender and Windows Firewall

**Moonlight Logs (please attach)**
[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/7264582/moonlight.log)

**Additional context**
Worked fine on the 32 bit Raspbian OS.

The vc4 driver is loaded so either moonlight is looking for it in some kind of nonstandard directory or there is some other problem. I tried both with kms and fake kms and the result is the same.

**Comment by cgutman** [comment]
The Raspberry Pi HEVC codec requires out-of-tree patches for FFmpeg to add stateless V4L2 codec support.

You’ll need to replace the stock FFmpeg libraries with a version with those patches integrated, such as this branch which I use for the Raspbian packages: https://github.com/cgutman/FFmpeg/tree/moonlight-rpi_4_3_2

**Comment by Barborica-Alexandru** [comment]
Hi thanks for the quick reply. I tried compiling that branch and am still getting this error in FFmpeg 
```
On branch moonlight-rpi_4_3_2
Your branch is up to date with 'origin/moonlight-rpi_4_3_2'.
```
```
00:00:13 - FFmpeg: [hevc_v4l2m2m @ 0x34347e60] v4l2 output format not supported
00:00:13 - FFmpeg: [hevc_v4l2m2m @ 0x34347e60] Could not find a valid device
00:00:13 - FFmpeg: [hevc_v4l2m2m @ 0x34347e60] can't configure decoder
```
Also I had to change the include line from drm_fourcc.h to libdrm/drm_fourcc.h for ffmpeg to compile. Am i supposed to uninstall ffmpeg-libs? Moonlight tells me its missing libavcodec.so.58 if I uninstall it.

**Comment by cgutman** [comment]
yes, you need to make Moonlight is loading the FFmpeg libraries you built (which is probably most easily done by removing the existing ones).

The v4l2m2m messages you are seeing are from the FFmpeg stateful v4l2 backend. It is expected to fail because the HEVC codec requires the stateless API. The stateless codec is called v4l2requests.

If you aren’t seeing messages from v4l2requests, that means you either haven’t properly enabled it when building FFmpeg or the libraries you but aren’t the ones being loaded (which sounds like the case based on your report of libavcodec errors when you remove the system libraries).

Did you remember to `make install` after you built libraries?

**Comment by Barborica-Alexandru** [comment]
I think the problem was that I compiled moonlight-qt with when I had the default ffmpeg-devel package installed. So now I'm trying to build moonlight again but started from scratch and only built FFMpeg manually. Right now I'm stuck at compiling moonlight with the error streaming/session.cpp:233:2: error: #error No video decoding libraries available!.
FFMpeg probably needs to be built with some more libraries or something so i'm just going to try to cram as many as possible into the build and see if that changes anything.

**Comment by Bobbar** [comment]
Will the recent RPI V4L2 stateful decode updates have any benefit for current/future Moonlight HVEC decoding?

https://github.com/raspberrypi/firmware/commit/fde2999b0702acfbc57751421788a579023e2ce8

**Comment by cgutman** [comment]
MMAL isn't required. We build the Moonlight for Tegra (aarch64) version without MMAL.

It should work fine on the Pi without MMAL (though V4L2M2M H.264 decoding is much slower than MMAL or V4L2 HEVC decoding). As long as your host has HEVC encoding (GTX 900-series or later) and you meet [the other requirements](https://github.com/moonlight-stream/moonlight-docs/wiki/Installing-Moonlight-Qt-on-Raspberry-Pi-4#hevc-support) for HEVC, it should work well with HEVC even without MMAL.

**Comment by cgutman** [comment]
Can you attach your `ffbuild/config.log` from the FFmpeg build you did? IIRC, the v4l2requests stuff has a bad habit of silently (partially) disabling itself if some dependency wasn't met (usually missing/old kernel headers). That's why we had to manually install `linux-libc-dev` to build v4l2requests successfully https://github.com/cgutman/moonlight-packaging/commit/759e361f2fc01b745a5d8df163ea5a83a83e9362

Please also attach the output of `ffmpeg -hwaccels` and `ffmpeg -decoders`.

**Comment by Barborica-Alexandru** [comment]
Ok I got it all attached here.

[ffmpeg-hwaccels.log](https://github.com/moonlight-stream/moonlight-qt/files/7358308/ffmpeg-hwaccels.log)
[ffmpeg-decoders.log](https://github.com/moonlight-stream/moonlight-qt/files/7358309/ffmpeg-decoders.log)
[config.log](https://github.com/moonlight-stream/moonlight-qt/files/7358310/config.log)

**Comment by cgutman** [comment]
Yep, it's a header issue:
```
check_cc hevc_v4l2_request linux/videodev2.h int i = V4L2_PIX_FMT_HEVC_SLICE;
test_code cc linux/videodev2.h int i = V4L2_PIX_FMT_HEVC_SLICE;
test_cc
BEGIN /tmp/ffconf.91QWj46h/test.c
    1	#include <linux/videodev2.h>
    2	int main(void) { int i = V4L2_PIX_FMT_HEVC_SLICE;; return 0; }
END /tmp/ffconf.91QWj46h/test.c
gcc -D_ISOC99_SOURCE -D_FILE_OFFSET_BITS=64 -D_LARGEFILE_SOURCE -D_POSIX_C_SOURCE=200112 -D_XOPEN_SOURCE=600 -DPIC -I/usr/include/libdrm -std=c11 -fomit-frame-pointer -fPIC -pthread -I/usr/include/libdrm -c -o /tmp/ffconf.91QWj46h/test.o /tmp/ffconf.91QWj46h/test.c
/tmp/ffconf.91QWj46h/test.c: In function 'main':
/tmp/ffconf.91QWj46h/test.c:2:26: error: 'V4L2_PIX_FMT_HEVC_SLICE' undeclared (first use in this function); did you mean 'V4L2_PIX_FMT_MPEG2_SLICE'?
    2 | int main(void) { int i = V4L2_PIX_FMT_HEVC_SLICE;; return 0; }
      |                          ^~~~~~~~~~~~~~~~~~~~~~~
      |                          V4L2_PIX_FMT_MPEG2_SLICE
/tmp/ffconf.91QWj46h/test.c:2:26: note: each undeclared identifier is reported only once for each function it appears in
```

You can just modify your local copy of `videodev2.h` to add:
```
#define V4L2_PIX_FMT_HEVC_SLICE v4l2_fourcc('S', '2', '6', '5') /* HEVC parsed slices */
```

**Comment by Barborica-Alexandru** [comment]
ok so I have 3 videodev2.h files:
/usr/include/linux/videodev2.h
/usr/src/linux-headers-5.10.73-v8/include/uapi/linux/videodev2.h
/usr/src/linux-headers-5.10.73-v8/include/linux/videodev2.h

I tried modifying the first one and it didn't work. I'm going to try the second one now and see if it helps. The kernel is built by me and slightly modified, maybe I missed a kernel parameter when I configured the kernel? This is my kernel config:
[config5.10.60.txt](https://github.com/moonlight-stream/moonlight-qt/files/7359013/config5.10.60.txt)

**Comment by cgutman** [comment]
I'm not totally sure either. The FFmpeg `./configure` script is pretty complicated and it's not totally clear what depends on what.

Check the end of the `./configure` terminal output and see if you see a message about `v4l2requests`. I think when I had issues before, it said it was disabled due to missing dependencies or something.

**Comment by cgutman** [comment]
h264_v4l2m2m is not actually a hwaccel. It's a completely separate decoder.

That configure output does look correct, but can you tee the full `./configure` output to a file and attach it so I can read the whole thing?

`./configure 2>&1 | tee configure.log`

**Comment by Barborica-Alexandru** [comment]
> 
> 
> h264_v4l2m2m is not actually a hwaccel. It's a completely separate decoder.
> 
> That configure output does look correct, but can you tee the full `./configure` output to a file and attach it so I can read the whole thing?
> 
> `./configure <options> 2>&1 | tee configure.log`

Here it is
[configure.log](https://github.com/moonlight-stream/moonlight-qt/files/7360170/configure.log)

**Comment by cgutman** [comment]
Moonlight doesn't use the `ffmpeg` binary itself. It uses the `libavcodec.so` and `libavutil.so` libraries that are included with it.

Please run `ldd <path to moonlight-qt>` and attach the output.

**Comment by cgutman** [comment]
Oh right, there’s no libavcodec.so here because you’re using a static build of FFmpeg. You should do a clean rebuild of Moonlight to make sure it picks up the new libavcodec.a library.

**Comment by cgutman** [comment]
Can you post the entire Moonlight log output, not just an excerpt?

**Comment by Barborica-Alexandru** [comment]
Here it is
[moonlight.log](https://github.com/moonlight-stream/moonlight-qt/files/7361074/moonlight.log)

**Comment by Originalimoc** [comment]
I replicated last post on Arch. Compiles are proceed but results are same as Raspberry Pi OS Legacy(buster) with following wiki install.
Results: 1440p60 launches, but only running at ~15FPS. 4k60 start just lockdown the terminal with a black screen. Force HW/HEVC enabled, CPU @2k60 is at 80% single core.
Confused.

**Comment by Originalimoc** [comment]
Debug done. It indeed works. Your working better because no desktop environment eating CMA memory. 2k120@80-90FPS uses ~260M while 4k60 uses ~400M. Set it to 700M by `dtoverlay=vc4-kms-v3d-pi4,cma-size=746586112` making it working while KDE Plasma also running. Now only this...:```
00:02:37 - SDL Info (0): Video decode unit queue overflow
00:02:37 - SDL Info (0): IDR frame request sent
00:02:37 - SDL Info (0): Waiting for IDR frame
00:02:39 - SDL Info (0): Video decode unit queue overflow
00:02:39 - SDL Info (0): Waiting for IDR frame
00:02:39 - SDL Info (0): IDR frame request sent
00:02:39 - SDL Info (0): Waiting for IDR frame
```

**Comment by Bobbar** [comment]
It's probably literally unable to keep up. Some overclocking may help at those resolutions. And FWIW, I'm finding that the 64bit Raspi OS handles high resolutions and bandwidth much better than the 32bit builds.

**Comment by Originalimoc** [comment]
Somewhat should. Just try vlc 32bit vs 64bit on large video, 64bit performs much better. I'll try OC gpu_freq later.

**Comment by Bobbar** [comment]
Have you set an overclock with `arm_freq` or set `hdmi_enable_4kp60`?  You'll need at least one of those for proper 4k rendering. The highest resolution I can reliably stream is 1440p (2560x1440); 11ms avg decode time. Anything above that is a mess. 

There's a lot of Pi specific optimizations you may be missing out on with your setup as well.

**Comment by Originalimoc** [comment]
Both set, 2k120 HDMI signal with 2k120 moonlight settings with actual gaming PC FPS 80-90 FPS is good enough. PC monitor is 2k so unless I set a virtual 4k screen to make it make sense to use 4k.

**Comment by Originalimoc** [comment]
Given https://www.raspberrypi.com/documentation/computers/config_txt.html#overclocking

600Mhz is acceptable and there's a hevc_freq. I'm not pushing hard enough huh😂(only 550). Later.

**Comment by Bobbar** [comment]
Yeah that 4k60 parameter isn't in raspi-config for any rpi OS as far as I know. If I remember correctly there's upstream commits that will make it unnecessary eventually. 

Here's what I'm running:

```
over_voltage=7
arm_freq=2000
gpu_freq=650
```

Temps stay under 55c with a nice little passive aluminum enclosure I found. 

But no matter what you push it to I'm not sure it would quite handle those frame rates.

What's your avg decoding, delay and render times from the moonlight logs?

**Comment by Originalimoc** [comment]
gpu_freq=600 working. Hopefully not like GDDR6X which higher clock might be slower due to error detection.
And no sound, turns out you need login to TTY to launch, not non-login and launching from remote ssh for no password  for convenience sake🌚
