### ISSUE TITLE
Windows changing resolution to 720p trying to play using 1440p

### ISSUE THREAD

**Issue by Bisewski** [cgutman/moonlight-qt#655]
I'm using the Mac client (3.1.4) and when I try to set resolution to 1440p, host (Windows) changes the screen resolution to 720p. The game runs at 1440p though, but some games have a bad image quality this way. The same does not happen when using 1080p.

**Comment by cgutman** [comment]
We've got an FAQ that covers this - https://github.com/moonlight-stream/moonlight-docs/wiki/Frequently-Asked-Questions#why-does-my-host-pc-resolution-change-to-720p-when-i-start-streaming

**Comment by Krutsch** [comment]
@cgutman  Thanks, but the custom program to stream my entire desktop has HDR checked as no. The only option to start HDR is via Steam for me, which sets the resolution to 720p
