### ISSUE TITLE
Moonlight doesn't display HDR content correctly on an internal XDR display (MacOS).

### ISSUE THREAD

**Issue by Cloudbarrage** [cgutman/moonlight-qt#956]
It seems to work sometimes, but other times the picture is washed out.

**Reproduction**
The most reliable way to reproduce the issue is:
- Connect to the desktop via the mstsc.exe trick (with hdr enabled on the Server PC)
- Disconnect the connection
- Quit mstsc.exe
- Reconnect

**Workaround**
- Disable HDR on the Server PC
- Reenable HDR on the Server PC

**Screenshots**
Working as intended:
(The completely white window is a bug in MacOS for screenshots of HDR content, it looks better in Moonlight. This bug makes it easy to tell that moonlight works properly with HDR enabled.)
<img width="1512" alt="WorkingHDR" src="https://user-images.githubusercontent.com/9503253/218912587-03046778-d96e-4a79-89f6-35e8370809e3.png">

Washed out:
<img width="1512" alt="WashedOut" src="https://user-images.githubusercontent.com/9503253/218912562-d1706cdc-133e-4bb0-bce4-b54ecc9a9016.png">

**Affected games**
- Windows desktop, Hogwarts Legacy

**Moonlight settings (please complete the following information)**
HDR turned on.
Changing resolution, fps or windowed mode din't alter the results.

**Client PC details (please complete the following information)**
- 14" M1 MacBook Pro running MacOS 13.2 (22D49)
- Moonlight 4.3.1

**Server PC details (please complete the following information)**
- OS: Windows 11 22H2 (10.0.22621.1194) 
- GeForce Experience version: 3.27.0.112
- Nvidia GPU driver: 528.49

**Comment by msirianni** [comment]
Did you find a solution to this? I'm noticing the same behavior.
